# Generated by Django 3.1.4 on 2021-01-06 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orchestra_name', models.CharField(max_length=150, verbose_name='楽団名')),
                ('orchestra_name_kana', models.CharField(max_length=150, verbose_name='楽団名（かな）')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orchestra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
