# Generated by Django 3.1.4 on 2021-01-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchestra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orchestra',
            options={'verbose_name': 'orchestra', 'verbose_name_plural': '楽団'},
        ),
        migrations.RemoveField(
            model_name='orchestra',
            name='user',
        ),
        migrations.AddField(
            model_name='orchestra',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村番地'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='admin_users',
            field=models.ForeignKey(default='hajime.fujita@gmail.com', on_delete=django.db.models.deletion.PROTECT, related_name='orchestra', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orchestra',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='設立年月日'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='building',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='country',
            field=models.CharField(default='日本', editable=False, max_length=15, verbose_name='国'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='email',
            field=models.EmailField(default='hajime.fujita@gmail.com', max_length=254, unique=True, verbose_name='メールアドレス'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orchestra',
            name='orchestra_type',
            field=models.CharField(choices=[('吹奏楽団', '吹奏楽団'), ('交響楽団', '交響楽団'), ('合唱団', '合唱団'), ('ブラスバンド', 'ブラスバンド'), ('アンサンブル', 'アンサンブル'), ('その他', 'その他')], default=1, max_length=20, verbose_name='種別'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orchestra',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号（ハイフンなし）'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='prefecture',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='電話番号（ハイフンなし）'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='orchestra',
            table='Orchestra',
        ),
    ]
