# Generated by Django 3.1.4 on 2021-01-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0002_auto_20210106_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestra',
            name='admin_users',
        ),
    ]
