# Generated by Django 3.1.4 on 2021-01-06 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchestra', '0003_remove_orchestra_admin_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestra',
            name='admin_users',
            field=models.ForeignKey(default='503bdaa23e7e4ce6b7fb337dc40e6dcb', on_delete=django.db.models.deletion.PROTECT, related_name='orchestra', to='users.user'),
            preserve_default=False,
        ),
    ]
