# Generated by Django 3.1.4 on 2021-01-06 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0004_orchestra_admin_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestra',
            name='id',
        ),
        migrations.AddField(
            model_name='orchestra',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
