# Generated by Django 3.1.4 on 2021-01-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0005_auto_20210106_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestra',
            name='id',
        ),
    ]
