# Generated by Django 3.1.4 on 2020-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201228_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_kana',
            field=models.CharField(default=999, max_length=150, verbose_name='名（かな）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_kana',
            field=models.CharField(default=111, max_length=150, verbose_name='姓（かな）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='old_last_name',
            field=models.CharField(default=111, max_length=150, verbose_name='旧姓'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='old_last_name_kana',
            field=models.CharField(default=111, max_length=150, verbose_name='旧姓（かな）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='姓'),
        ),
    ]
