# Generated by Django 3.1.4 on 2020-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201229_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='old_last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='旧姓'),
        ),
        migrations.AlterField(
            model_name='user',
            name='old_last_name_kana',
            field=models.CharField(max_length=150, null=True, verbose_name='旧姓（かな）'),
        ),
    ]
