# Generated by Django 3.1.4 on 2020-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201229_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.CharField(max_length=30, null=True, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='日本', editable=False, max_length=15, verbose_name='国'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.SmallIntegerField(null=True, verbose_name='郵便番号（ハイフンなし）'),
        ),
        migrations.AddField(
            model_name='user',
            name='prefecture',
            field=models.CharField(max_length=5, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='男性', max_length=4, verbose_name='性別'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.SmallIntegerField(null=True, verbose_name='電話番号（ハイフンなし）'),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(max_length=300, null=True, verbose_name='URL'),
        ),
    ]
