# Generated by Django 3.1.4 on 2020-12-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201229_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='building',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='建物名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='old_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='旧姓'),
        ),
        migrations.AlterField(
            model_name='user',
            name='old_last_name_kana',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='旧姓（かな）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='郵便番号（ハイフンなし）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='電話番号（ハイフンなし）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
