# Generated by Django 3.1.4 on 2020-12-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201229_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村番地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号（ハイフンなし）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='電話番号（ハイフンなし）'),
        ),
    ]
