# Generated by Django 3.1.4 on 2021-01-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0003_orchestra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orchestra',
        ),
    ]
