# Generated by Django 3.1.4 on 2021-01-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0009_auto_20210106_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orchestra',
        ),
    ]
