# Generated by Django 3.1.4 on 2021-01-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0017_auto_20210106_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orchestra',
        ),
    ]
